BACKUP DATABASE [ShelleySpecialOne]
TO DISK = N'D:\SQL-Server-Backups\HXCNAS2\MSSQLSERVER\On-Demand\ShelleySpecialOne-20190531-P1.bak',
DISK = N'D:\SQL-Server-Backups\HXCNAS2\MSSQLSERVER\On-Demand\ShelleySpecialOne-20190531-P2.bak'
WITH NOFORMAT, INIT, SKIP, NOREWIND, NOUNLOAD, COMPRESSION, MAXTRANSFERSIZE = 2097152, STATS = 5, BUFFERCOUNT = 100, BLOCKSIZE = 8192, STATS=10

