
RESTORE LOG [DATABASE_NAME] FROM  DISK = N'\\FullPathNAME\HERE\FileNAME_log_201903200257.trn' 
WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  MAXTRANSFERSIZE = 1048576
GO
RESTORE LOG [DATABASE_NAME] FROM  DISK = N'\\FullPathNAME\HERE\FileNAME_log_201903200843.trn' 
WITH  FILE = 1,  NORECOVERY,  
MOVE 'AdventureWorks2012_Data' TO 'D:\MyData\MyAdvWorks_Data.mdf',   
MOVE 'AdventureWorks2012_Log' TO 'F:\MyLog\MyAdvWorks_Log.ldf',  


NOUNLOAD,  MAXTRANSFERSIZE = 1048576
GO

PHILOG	ROWS	X:\PHILOG\PHILOG.mdf
PHILOG	LOG	X:\PHILOG\PHILOG_log.ldf
PHILOG	ROWS	T:\PHILOG\PHILOG_1.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_2.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_3.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_4.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_5.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_6.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_7.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_8.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_9.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_10.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_11.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_12.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_13.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_14.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_15.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_16.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_17.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_18.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_19.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_20.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_21.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_22.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_23.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_24.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_25.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_26.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_27.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_28.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_29.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_30.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_31.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_32.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_33.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_34.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_35.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_36.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_37.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_38.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_39.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_40.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_41.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_42.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_43.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_44.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_45.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_46.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_47.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_48.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_49.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_50.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_51.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_52.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_53.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_54.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_55.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_56.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_57.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_58.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_59.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_60.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_61.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_62.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_63.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_64.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_65.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_66.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_67.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_68.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_69.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_70.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_71.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_72.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_73.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_74.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_75.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_76.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_77.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_78.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_79.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_80.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_81.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_82.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_83.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_84.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_85.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_86.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_87.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_88.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_89.mdf
PHILOG	ROWS	T:\PHILOG\PHILOG_90.mdf
PHILOG	ROWS	X:\PHILOG\PHIAccessLog-2018-06.mdf
PHILOG	ROWS	X:\PHILOG\PHIAccessLog-2018-07.mdf
PHILOG	ROWS	X:\PHILOG\PHIAccessLog-2018-08.mdf
PHILOG	ROWS	X:\PHILOG\PHIAccessLog-2018-09.mdf
PHILOG	ROWS	X:\PHILOG\PHIAccessLog-2018-10.mdf


RESTORE DATABASE [PHILOG] FROM DISK  = N'F:\backup\PHILOG-20190430-1304-hxbprodb1copy.bak'
WITH FILE = 1, NOUNLOAD, STATS = 5, MAXTRANSFERSIZE = 4194302, BUFFERCOUNT = 100