
--ALTER DATABASE [ARCHIVE] SET PARTNER OFF
--RESTORE DATABASE [ARCHIVE] WITH NORECOVERY

--ALTER DATABASE [DI_PROCESS] SET PARTNER OFF
--RESTORE DATABASE [DI_PROCESS] WITH NORECOVERY

--ALTER DATABASE [di_sandbox] SET PARTNER OFF
--RESTORE DATABASE [di_sandbox] WITH NORECOVERY

--ALTER DATABASE [frodo_production] SET PARTNER OFF
--RESTORE DATABASE [frodo_production] WITH NORECOVERY

--ALTER DATABASE [HealthXSecurity] SET PARTNER OFF
--RESTORE DATABASE [HealthXSecurity] WITH NORECOVERY

--ALTER DATABASE [hxlog] SET PARTNER OFF
--RESTORE DATABASE [hxlog] WITH NORECOVERY

--ALTER DATABASE [PHILOG] SET PARTNER OFF
--RESTORE DATABASE [PHILOG] WITH NORECOVERY

--ALTER DATABASE [WORKSPACE] SET PARTNER OFF
--RESTORE DATABASE [WORKSPACE] WITH NORECOVERY